feat: parse big-number string as BigInt
niieani/hashids.js pull request #230
Opened 2020-03-08 16:17 UTC by juanluispaz

This pull request fix the issue #68

2020-12-18 05:44 UTC, niieani requested changes
May I ask you to rebase, use prettier formatting and remove the built files from the commit?
Thanks.

2021-07-14 13:22 UTC, simontaisne commented
Any chance this PR lands?

2021-07-24 08:24 UTC, niieani commented
Thanks @simontaisne, feel free to address my comments to @juanluispaz's PR and submit another PR, I'll be happy to merge and release it.

2021-07-24 08:26 UTC, niieani commented on lib/hashids.ts
> +      `Unable to encode the provided big-number string without lose information, due to lack of support for BigInt numbers in the current environment`,
```suggestion
      `Unable to encode the provided BigInt string without loss of information due to lack of support for BigInt type in the current environment`,
```

2023-05-24 03:33 UTC, niieani commented
superseded by https://github.com/niieani/hashids.js/pull/546

2023-05-24 03:33 UTC, closed without merging